version: "3.8"

services:
  postgres:
    image: postgres:18.3
    container_name: stockly-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: store_user
      POSTGRES_PASSWORD: store_password
      POSTGRES_DB: stockly_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
